name: Build & Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  
  
jobs:
    build:
        runs-on: macos-latest
        
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set Specific Xcode Version
          run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

        - name: Generate app-debug xcconfig
          run: echo "${{ secrets.DEBUG_XCCONFIG }}" > ./app-debug.xcconfig

        - name: Generate app-release xcconfig
          run: echo "${{ secrets.DEBUG_XCCONFIG }}" > ./app-release.xcconfig

        - name: 🛠️ Start Xcode Build
          run: |
            xcodebuild clean test \
            -project Health.xcodeproj \
            -scheme Health-DEBUG \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.4' \
            -xcconfig ./app-debug.xcconfig
